/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per1;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MAWIL
 */
public class JFBuscarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form JFBuscarPaciente
     */
    public JFBuscarPaciente() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadoctor = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PACIENTE BUSCAR");

        jLabel2.setText("CEDULA / NOMBRE / APELLIDO / CORREO:");

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        tadoctor.setColumns(20);
        tadoctor.setRows(5);
        jScrollPane1.setViewportView(tadoctor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnbuscar)
                .addGap(210, 210, 210))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnsalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel2)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsalir)
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        if(tfbuscar.getText() != null){
            if(consultar_cedula(DB, tfbuscar.getText()) != 0){
                Paciente pac = new Paciente(null, null, null, tfbuscar.getText(), null, null, null, null, null, null, 0, null);
                ObjectSet resul = DB.get(pac);

                while(resul.hasNext()){
                    tadoctor.setText(resul.next().toString());
                }
            }else if(consultar_nombre(DB, tfbuscar.getText()) != 0){
                Paciente pac = new Paciente(null, null, null, null, tfbuscar.getText(), null, null, null, null, null, 0, null);
                ObjectSet resul = DB.get(pac);

                while(resul.hasNext()){
                    tadoctor.setText(resul.next().toString());
                }
            }
            else if(consultar_apellido(DB, tfbuscar.getText()) != 0){
                Paciente pac = new Paciente(null, null, null, null, null, tfbuscar.getText(), null, null, null, null, 0, null);
                ObjectSet resul = DB.get(pac);

                while(resul.hasNext()){
                    tadoctor.setText(resul.next().toString());
                }
            }else if(consultar_correo(DB, tfbuscar.getText()) != 0){
                Paciente pac = new Paciente(null, null, null, null, null, null, null, tfbuscar.getText(), null, null, 0, null);
                ObjectSet resul = DB.get(pac);

                while(resul.hasNext()){
                    tadoctor.setText(resul.next().toString());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "No se encntraron datos");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "INGRESE EL CEDULA O NOMBRE O APELLIDO O CORREO DEL PACIENTE QUE DESEA BUSCAR");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFMenu men = new JFMenu();
        men.setVisible(true);
    }//GEN-LAST:event_btnsalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tadoctor;
    private javax.swing.JTextField tfbuscar;
    // End of variables declaration//GEN-END:variables

    public static int consultar_cedula(ObjectContainer base, String per_cedula){
        Paciente pac = new Paciente(null, null, null, per_cedula, null, null, null, null, null, null, 0, null);
        ObjectSet resul = base.get(pac);
        return resul.size();
    }
    
    public static int consultar_nombre(ObjectContainer base, String per_nombre){
        Paciente pac = new Paciente(null, null, null, null, per_nombre, null, null, null, null, null, 0, null);
        ObjectSet resul = base.get(pac);
        return resul.size();
    }
    
    public static int consultar_apellido(ObjectContainer base, String per_apellido){
        Paciente pac = new Paciente(null, null, null, null, null, per_apellido, null, null, null, null, 0, null);
        ObjectSet resul = base.get(pac);
        return resul.size();
    }
    
    public static int consultar_correo(ObjectContainer base, String per_correo){
        Paciente pac = new Paciente(null, null, null, null, null, null, null, per_correo, null, null, 0, null);
        ObjectSet resul = base.get(pac);
        return resul.size();
    }
}
