/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per1;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MAWIL
 */
public class JFDoctor extends javax.swing.JFrame {

    Validaciones vali = new Validaciones();
    
    /**
     * Creates new form JFDoctor
     */
    public JFDoctor() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btinsertardoctor = new javax.swing.JButton();
        btmodificardoctor = new javax.swing.JButton();
        bteliminardoctor = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfespecialidaddoctor = new javax.swing.JTextField();
        tfcategoriadoctor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfnacimientodoctor = new com.toedter.calendar.JDateChooser();
        tftelefonodoctor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfsexodoctor = new javax.swing.JTextField();
        tfsangredoctor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfcorreodoctor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdirecciondoctor = new javax.swing.JTextField();
        tfapellidodoctor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfnombredoctor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfceduladoctor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("DOCTOR CREAR / MODIFICAR / ELIMINAR");

        btinsertardoctor.setText("CREAR");
        btinsertardoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertardoctorActionPerformed(evt);
            }
        });

        btmodificardoctor.setText("MODIFICAR");
        btmodificardoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificardoctorActionPerformed(evt);
            }
        });

        bteliminardoctor.setText("ELIMINAR");
        bteliminardoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminardoctorActionPerformed(evt);
            }
        });

        btsalir.setText("SALIR");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminardoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodificardoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btinsertardoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btinsertardoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btmodificardoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(bteliminardoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel11.setText("ESPECIALIDAD:");

        jLabel12.setText("CATEGORIA:");

        jLabel10.setText("FECHA DE NACIMIENTO:");

        tftelefonodoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tftelefonodoctorFocusLost(evt);
            }
        });

        jLabel9.setText("TELEFONO:");

        jLabel8.setText("SEXO:");

        tfsexodoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfsexodoctorFocusLost(evt);
            }
        });

        jLabel7.setText("TIPO DE SANGRE:");

        jLabel6.setText("CORREO:");

        jLabel5.setText("DIRECCION:");

        tfapellidodoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfapellidodoctorFocusLost(evt);
            }
        });

        jLabel4.setText("APELLIDO:");

        tfnombredoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfnombredoctorFocusLost(evt);
            }
        });

        jLabel2.setText("CEDULA:");

        tfceduladoctor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfceduladoctorFocusLost(evt);
            }
        });

        jLabel3.setText("NOMBRE:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(tfsangredoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(tfcorreodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(tfapellidodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(tfdirecciondoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tfnombredoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tfceduladoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(tfsexodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(tftelefonodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(tfnacimientodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfespecialidaddoctor)
                            .addComponent(tfcategoriadoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfceduladoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfnombredoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfapellidodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdirecciondoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfcorreodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsangredoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsexodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tftelefonodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tfnacimientodoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcategoriadoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfespecialidaddoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmodificardoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificardoctorActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap"); 
        Doctor doc = new Doctor(null, null, tfceduladoctor.getText(), null, null, null, null, null, null, 0, null);        
        try{
            ObjectSet resul = DB.get(doc);        
            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :("); 
            }
            else
            {
                int telefono = Integer.parseInt(tftelefonodoctor.getText());
                Doctor mdoc = (Doctor)resul.next();
                mdoc.setDoc_categoria(tfcategoriadoctor.getText());
                mdoc.setDoc_esp_codigo(tfespecialidaddoctor.getText());
                mdoc.setPer_apellido(tfapellidodoctor.getText());
                mdoc.setPer_correo(tfcorreodoctor.getText());
                mdoc.setPer_direccion(tfdirecciondoctor.getText());
                mdoc.setPer_nacimiento(tfnacimientodoctor.getDate());
                mdoc.setPer_nombre(tfnombredoctor.getText());
                mdoc.setPer_sexo(tfsexodoctor.getText());
                mdoc.setPer_telefono(telefono);
                mdoc.setPer_tiposangre(tfsangredoctor.getText());
                DB.set(mdoc);
                JOptionPane.showMessageDialog(rootPane, "Datos actualizados exitosamente :("); 
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true); 
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se actualizaron exitosamente :("); 
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btmodificardoctorActionPerformed

    private void btinsertardoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertardoctorActionPerformed
        // TODO add your handling code here:
        int telefono = Integer.parseInt(tftelefonodoctor.getText());
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap"); 
        Doctor doc = new Doctor(tfespecialidaddoctor.getText(), tfcategoriadoctor.getText(), tfceduladoctor.getText(), tfnombredoctor.getText(), tfapellidodoctor.getText(), tfdirecciondoctor.getText(), tfcorreodoctor.getText(), tfsangredoctor.getText(), tfsexodoctor.getText(), telefono, tfnacimientodoctor.getDate());
        try{
            if(Comprobar_Doctor(DB, tfceduladoctor.getText()) == 0){ 
                DB.store(doc);
                DB.commit();
                JOptionPane.showMessageDialog(rootPane, "Datos guardados exitosamente :)");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true); 
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Estos Datos ya existen :|");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se guardados exitosamente :("); 
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btinsertardoctorActionPerformed

    private void bteliminardoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminardoctorActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap"); 
        Doctor doc = new Doctor(null, null, tfceduladoctor.getText(), null, null, null, null, null, null, 0, null);        
        try{
            ObjectSet resul = DB.get(doc);
        
            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :("); 
            }
            else
            {
                Doctor edoc = (Doctor)resul.next();
                DB.delete(edoc);
                JOptionPane.showMessageDialog(rootPane, "Datos eliminados exitosamente :("); 
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true); 
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se eliminaros exitosamente :("); 
        }finally{
            DB.close();
        }        
    }//GEN-LAST:event_bteliminardoctorActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFMenu men = new JFMenu();
        men.setVisible(true); 
    }//GEN-LAST:event_btsalirActionPerformed

    private void tfceduladoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfceduladoctorFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tfceduladoctor.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique la cedula");
        }
    }//GEN-LAST:event_tfceduladoctorFocusLost

    private void tfnombredoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfnombredoctorFocusLost
        // TODO add your handling code here:
        if(vali.validaNombreoApellido(tfnombredoctor.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el nombre");
        }
    }//GEN-LAST:event_tfnombredoctorFocusLost

    private void tfapellidodoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfapellidodoctorFocusLost
        // TODO add your handling code here:
        if(vali.validaNombreoApellido(tfapellidodoctor.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el apellido");
        }
    }//GEN-LAST:event_tfapellidodoctorFocusLost

    private void tfsexodoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfsexodoctorFocusLost
        // TODO add your handling code here:
        if(vali.validasexo(tfsexodoctor.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el sexo M O F");
        }
    }//GEN-LAST:event_tfsexodoctorFocusLost

    private void tftelefonodoctorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tftelefonodoctorFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tftelefonodoctor.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el numero telefonico");
        }
    }//GEN-LAST:event_tftelefonodoctorFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteliminardoctor;
    private javax.swing.JButton btinsertardoctor;
    private javax.swing.JButton btmodificardoctor;
    private javax.swing.JButton btsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfapellidodoctor;
    private javax.swing.JTextField tfcategoriadoctor;
    private javax.swing.JTextField tfceduladoctor;
    private javax.swing.JTextField tfcorreodoctor;
    private javax.swing.JTextField tfdirecciondoctor;
    private javax.swing.JTextField tfespecialidaddoctor;
    private com.toedter.calendar.JDateChooser tfnacimientodoctor;
    private javax.swing.JTextField tfnombredoctor;
    private javax.swing.JTextField tfsangredoctor;
    private javax.swing.JTextField tfsexodoctor;
    private javax.swing.JTextField tftelefonodoctor;
    // End of variables declaration//GEN-END:variables

    public static int Comprobar_Doctor(ObjectContainer base, String per_cedula){
        Doctor doc = new Doctor(null, null, per_cedula, null, null, null, null, null, null, 0, null);
        ObjectSet resul = base.get(doc);
        return resul.size();
    }
}
