/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per1;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MAWIL
 */
public class JFPaciente extends javax.swing.JFrame {

    /**
     * Creates new form JFPaciente
     */
    public JFPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfcedulapaciente = new javax.swing.JTextField();
        tfnombrepaciente = new javax.swing.JTextField();
        btmodificarpaciente = new javax.swing.JButton();
        btinsertarpaciente = new javax.swing.JButton();
        bteliminarpaciente = new javax.swing.JButton();
        btpaciente = new javax.swing.JButton();
        tfapellipaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdireccionpaciente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcorreopaciente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfsangrepaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfsexopaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tftelefonopaciente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfcedularesponsablepaciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfpesopaciente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfnacimientopaciente = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tppaciente = new javax.swing.JTable();
        tfestaturapaciente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PACIENTE INGRESAR / MODIFICAR / ELIMINAR");

        jLabel2.setText("CEDULA:");

        jLabel3.setText("NOMBRE:");

        btmodificarpaciente.setText("MODIFICAR");
        btmodificarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarpacienteActionPerformed(evt);
            }
        });

        btinsertarpaciente.setText("INSERTAR");
        btinsertarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertarpacienteActionPerformed(evt);
            }
        });

        bteliminarpaciente.setText("ELIMINAR");
        bteliminarpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarpacienteActionPerformed(evt);
            }
        });

        btpaciente.setText("SALIR");
        btpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpacienteActionPerformed(evt);
            }
        });

        jLabel4.setText("APELLIDO:");

        jLabel5.setText("DIRECCION:");

        jLabel6.setText("CORREO:");

        jLabel7.setText("TIPO DE SANGRE:");

        jLabel8.setText("SEXO:");

        jLabel9.setText("TELEFONO:");

        jLabel10.setText("FECHA DE NACIMIENTO:");

        jLabel11.setText("CEDULA DE RESPONSABLE:");

        jLabel12.setText("PESO:");

        tppaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CEDULA", "NOMBRE", "APELLIDO", "DIRECCION", "CORREO", "CATEGORIA"
            }
        ));
        jScrollPane1.setViewportView(tppaciente);

        jLabel14.setText("ESTATURA:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfpesopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfsangrepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfcorreopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfapellipaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdireccionpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfsexopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(tftelefonopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfnacimientopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(tfcedularesponsablepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfnombrepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfcedulapaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(tfestaturapaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btinsertarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmodificarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bteliminarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(253, 253, 253))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfcedulapaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombrepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btmodificarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btinsertarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfapellipaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdireccionpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfcorreopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsangrepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsexopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tftelefonopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(tfnacimientopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tfcedularesponsablepaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfpesopaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfestaturapaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmodificarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarpacienteActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Paciente pac = new Paciente(null, null, null, tfcedulapaciente.getText(), null, null, null, null, null, null, 0, null);
        try{
            ObjectSet resul = DB.get(pac);
            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :(");
            }
            else
            {
                int telefono = Integer.parseInt(tftelefonopaciente.getText());
                Paciente mpac = (Paciente)resul.next();
                mpac.setPac_estatura(tfestaturapaciente.getText());
                mpac.setPac_peso(tfpesopaciente.getText());
                mpac.setPac_res_cedula(tfcedularesponsablepaciente.getText());
                mpac.setPer_apellido(tfapellipaciente.getText());
                mpac.setPer_cedula(tfcedulapaciente.getText());
                mpac.setPer_correo(tfcorreopaciente.getText());
                mpac.setPer_direccion(tfdireccionpaciente.getText());
                mpac.setPer_nacimiento(tfnacimientopaciente.getDate());
                mpac.setPer_nombre(tfnombrepaciente.getText());
                mpac.setPer_sexo(tfsexopaciente.getText());
                mpac.setPer_telefono(telefono);
                mpac.setPer_tiposangre(tfsangrepaciente.getText());
                DB.set(mpac);
                limpiarDatos();
                JOptionPane.showMessageDialog(rootPane, "Datos actualizados exitosamente :(");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true); 
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se actualizaron exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btmodificarpacienteActionPerformed

    private void btinsertarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertarpacienteActionPerformed
        // TODO add your handling code here:
        int telefono = Integer.parseInt(tftelefonopaciente.getText());
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Paciente pac = new Paciente(tfcedularesponsablepaciente.getText(), tfpesopaciente.getText(), tfestaturapaciente.getText(), tfcedulapaciente.getText(), tfnombrepaciente.getText(), tfapellipaciente.getText(), tfdireccionpaciente.getText(), tfcorreopaciente.getText(), tfsangrepaciente.getText(), tfsexopaciente.getText(), telefono, tfnacimientopaciente.getDate());
        try{
            if(Comprobar_Paciente(DB, tfcedulapaciente.getText()) == 0){
                DB.store(pac);
                DB.commit();
                limpiarDatos();
                JOptionPane.showMessageDialog(rootPane, "Datos guardados exitosamente :)");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true); 
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Estos Datos ya existen :|");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se guardados exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btinsertarpacienteActionPerformed

    private void bteliminarpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarpacienteActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Paciente pac = new Paciente(null, null, null, tfcedulapaciente.getText(), null, null, null, null, null, null, 0, null);
        try{
            ObjectSet resul = DB.get(pac);

            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :(");
            }
            else
            {
                Paciente epac = (Paciente)resul.next();
                DB.delete(epac);
                limpiarDatos();
                JOptionPane.showMessageDialog(rootPane, "Datos eliminados exitosamente :(");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true); 
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se eliminaros exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_bteliminarpacienteActionPerformed

    private void btpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpacienteActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFMenu men = new JFMenu();
        men.setVisible(true); 
    }//GEN-LAST:event_btpacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteliminarpaciente;
    private javax.swing.JButton btinsertarpaciente;
    private javax.swing.JButton btmodificarpaciente;
    private javax.swing.JButton btpaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfapellipaciente;
    private javax.swing.JTextField tfcedulapaciente;
    private javax.swing.JTextField tfcedularesponsablepaciente;
    private javax.swing.JTextField tfcorreopaciente;
    private javax.swing.JTextField tfdireccionpaciente;
    private javax.swing.JTextField tfestaturapaciente;
    private com.toedter.calendar.JDateChooser tfnacimientopaciente;
    private javax.swing.JTextField tfnombrepaciente;
    private javax.swing.JTextField tfpesopaciente;
    private javax.swing.JTextField tfsangrepaciente;
    private javax.swing.JTextField tfsexopaciente;
    private javax.swing.JTextField tftelefonopaciente;
    private javax.swing.JTable tppaciente;
    // End of variables declaration//GEN-END:variables

    public void limpiarDatos(){
        tfapellipaciente.setText("");
        tfcedulapaciente.setText("");
        tfcedularesponsablepaciente.setText("");
        tfcorreopaciente.setText("");
        tfdireccionpaciente.setText("");
        tfestaturapaciente.setText("");
        tfnombrepaciente.setText("");
        tfpesopaciente.setText("");
        tfsangrepaciente.setText("");
        tfsexopaciente.setText("");
        tftelefonopaciente.setText("");
    }
    
    public static int Comprobar_Paciente(ObjectContainer base, String per_cedula){
        Paciente pac = new Paciente(null, null, null, per_cedula, null, null, null, null, null, null, 0, null);
        ObjectSet resul = base.get(pac);
        return resul.size();
    }
}
