/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per1;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MAWIL
 */
public class JFResponsable extends javax.swing.JFrame {

    Validaciones vali = new Validaciones();
    
    /**
     * Creates new form JFResponsable
     */
    public JFResponsable() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfcedularesponsable = new javax.swing.JTextField();
        tfnombreresponsable = new javax.swing.JTextField();
        tfapellidoresponsable = new javax.swing.JTextField();
        tfdireccionresponsable = new javax.swing.JTextField();
        tfcorreoresponsable = new javax.swing.JTextField();
        tfsangreresponsable = new javax.swing.JTextField();
        tfsexoresponsable = new javax.swing.JTextField();
        tftelefonoresponsable = new javax.swing.JTextField();
        tfnacimientoresponsable = new com.toedter.calendar.JDateChooser();
        tfrelacionresponsable = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btinsertarresponsable = new javax.swing.JButton();
        btmodificarresponsable = new javax.swing.JButton();
        bteliminarresponsable = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("RESPONSABLE CREAR / MODIFICAR / ELIMINAR");

        tfcedularesponsable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcedularesponsableFocusLost(evt);
            }
        });

        tfnombreresponsable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfnombreresponsableFocusLost(evt);
            }
        });

        tfapellidoresponsable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfapellidoresponsableFocusLost(evt);
            }
        });

        tfsexoresponsable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfsexoresponsableFocusLost(evt);
            }
        });

        tftelefonoresponsable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tftelefonoresponsableFocusLost(evt);
            }
        });

        jLabel11.setText("RELACION:");

        jLabel10.setText("FECHA DE NACIMIENTO:");

        jLabel9.setText("TELEFONO:");

        jLabel8.setText("SEXO:");

        jLabel6.setText("CORREO:");

        jLabel7.setText("TIPO DE SANGRE:");

        jLabel5.setText("DIRECCION:");

        jLabel4.setText("APELLIDO:");

        jLabel3.setText("NOMBRE:");

        jLabel2.setText("CEDULA:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11)
                        .addGap(191, 191, 191))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(tfsangreresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(tfcorreoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(tfapellidoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(tfdireccionresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(tfnombreresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tfcedularesponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(tfsexoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(tftelefonoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfrelacionresponsable)
                                .addComponent(tfnacimientoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfcedularesponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnombreresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfapellidoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdireccionresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcorreoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsangreresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfsexoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tftelefonoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tfnacimientoresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfrelacionresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        btinsertarresponsable.setText("CREAR");
        btinsertarresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertarresponsableActionPerformed(evt);
            }
        });

        btmodificarresponsable.setText("MODIFICAR");
        btmodificarresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarresponsableActionPerformed(evt);
            }
        });

        bteliminarresponsable.setText("ELIMINAR");
        bteliminarresponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarresponsableActionPerformed(evt);
            }
        });

        btsalir.setText("SALIR");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodificarresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btinsertarresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btinsertarresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btmodificarresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(bteliminarresponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmodificarresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarresponsableActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Responsable res = new Responsable(null, tfcedularesponsable.getText(), null, null, null, null, null, null, 0, null);
        try{
            ObjectSet resul = DB.get(res);
            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :(");
            }
            else
            {
                int telefono = Integer.parseInt(tftelefonoresponsable.getText());
                Responsable mres = (Responsable)resul.next();
                mres.setRes_relacion_familiar(tfrelacionresponsable.getText());
                mres.setPer_apellido(tfapellidoresponsable.getText());
                mres.setPer_correo(tfcorreoresponsable.getText());
                mres.setPer_direccion(tfdireccionresponsable.getText());
                mres.setPer_nacimiento(tfnacimientoresponsable.getDate());
                mres.setPer_nombre(tfnombreresponsable.getText());
                mres.setPer_sexo(tfsexoresponsable.getText());
                mres.setPer_telefono(telefono);
                mres.setPer_tiposangre(tfsangreresponsable.getText());
                DB.set(mres);
                JOptionPane.showMessageDialog(rootPane, "Datos actualizados exitosamente :(");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se actualizaron exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btmodificarresponsableActionPerformed

    private void btinsertarresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertarresponsableActionPerformed
        // TODO add your handling code here:
        int telefono = Integer.parseInt(tftelefonoresponsable.getText());
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Responsable res = new Responsable(tfrelacionresponsable.getText(), tfcedularesponsable.getText(), tfnombreresponsable.getText(), tfapellidoresponsable.getText(), tfdireccionresponsable.getText(), tfcorreoresponsable.getText(), tfsangreresponsable.getText(), tfsexoresponsable.getText(), telefono, tfnacimientoresponsable.getDate());
        try{
            if(Comprobar_Responsable(DB, tfcedularesponsable.getText()) == 0){
                DB.store(res);
                DB.commit();
                JOptionPane.showMessageDialog(rootPane, "Datos guardados exitosamente :)");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Estos Datos ya existen :|");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se guardados exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btinsertarresponsableActionPerformed

    private void bteliminarresponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarresponsableActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Responsable res = new Responsable(null, tfcedularesponsable.getText(), null, null, null, null, null, null, 0, null);
        try{
            ObjectSet resul = DB.get(res);

            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :(");
            }
            else
            {
                Doctor edoc = (Doctor)resul.next();
                DB.delete(edoc);
                JOptionPane.showMessageDialog(rootPane, "Datos eliminados exitosamente :(");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se eliminaros exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_bteliminarresponsableActionPerformed

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFMenu men = new JFMenu();
        men.setVisible(true);
    }//GEN-LAST:event_btsalirActionPerformed

    private void tfcedularesponsableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcedularesponsableFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tfcedularesponsable.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique la cedula");
        }
    }//GEN-LAST:event_tfcedularesponsableFocusLost

    private void tfnombreresponsableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfnombreresponsableFocusLost
        // TODO add your handling code here:
        if(vali.validaNombreoApellido(tfnombreresponsable.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el nombre");
        }
    }//GEN-LAST:event_tfnombreresponsableFocusLost

    private void tfapellidoresponsableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfapellidoresponsableFocusLost
        // TODO add your handling code here:
        if(vali.validaNombreoApellido(tfapellidoresponsable.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el apellido");
        }
    }//GEN-LAST:event_tfapellidoresponsableFocusLost

    private void tfsexoresponsableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfsexoresponsableFocusLost
        // TODO add your handling code here:
        if(vali.validasexo(tfsexoresponsable.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique el sexo ingrese M O F");
        }
    }//GEN-LAST:event_tfsexoresponsableFocusLost

    private void tftelefonoresponsableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tftelefonoresponsableFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tftelefonoresponsableFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteliminarresponsable;
    private javax.swing.JButton btinsertarresponsable;
    private javax.swing.JButton btmodificarresponsable;
    private javax.swing.JButton btsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tfapellidoresponsable;
    private javax.swing.JTextField tfcedularesponsable;
    private javax.swing.JTextField tfcorreoresponsable;
    private javax.swing.JTextField tfdireccionresponsable;
    private com.toedter.calendar.JDateChooser tfnacimientoresponsable;
    private javax.swing.JTextField tfnombreresponsable;
    private javax.swing.JTextField tfrelacionresponsable;
    private javax.swing.JTextField tfsangreresponsable;
    private javax.swing.JTextField tfsexoresponsable;
    private javax.swing.JTextField tftelefonoresponsable;
    // End of variables declaration//GEN-END:variables
 
    public static int Comprobar_Responsable(ObjectContainer base, String per_cedula){
        Responsable res = new Responsable(null, per_cedula, null, null, null, null, null, null, 0, null);
        ObjectSet resul = base.get(res);
        return resul.size();
    } 
}
