/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package per1;

import com.db4o.Db4o;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import javax.swing.JOptionPane;

/**
 *
 * @author MAWIL
 */
public class JFReservaciones extends javax.swing.JFrame {
        
    Validaciones vali = new Validaciones();
    
    /**
     * Creates new form JFReservaciones
     */
    public JFReservaciones() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tfcodigoreservacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfcedulausuarioreservacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfceduladoctorreservacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcedulapacientereservacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfcedularesponsablereservacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jcfechayhorareservacion = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tasintomasreservacion = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btinsertarreservacion = new javax.swing.JButton();
        btmodificarreservacion = new javax.swing.JButton();
        btsalir = new javax.swing.JButton();
        bteliminarreservacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("RESERVACION CREAR / MODIFICAR / ELIMINAR");

        jLabel2.setText("CODIGO:");

        jLabel3.setText("CEDULA DEL USUARIO:");

        tfcedulausuarioreservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcedulausuarioreservacionFocusLost(evt);
            }
        });

        jLabel4.setText("CEDULA DEL DOCTOR:");

        tfceduladoctorreservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfceduladoctorreservacionFocusLost(evt);
            }
        });

        jLabel5.setText("CEDULA DEL PACIENTE:");

        tfcedulapacientereservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcedulapacientereservacionFocusLost(evt);
            }
        });

        jLabel6.setText("CEDULA DEL RESPONSABLE:");

        tfcedularesponsablereservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfcedularesponsablereservacionFocusLost(evt);
            }
        });

        jLabel8.setText("FECHA Y HORA:");

        tasintomasreservacion.setColumns(20);
        tasintomasreservacion.setRows(5);
        jScrollPane3.setViewportView(tasintomasreservacion);

        jLabel7.setText("SINTOMAS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfcedulausuarioreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfcodigoreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfceduladoctorreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcedulapacientereservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcedularesponsablereservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcfechayhorareservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcodigoreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfcedulausuarioreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfceduladoctorreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfcedulapacientereservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfcedularesponsablereservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jcfechayhorareservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btinsertarreservacion.setText("CREAR");
        btinsertarreservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinsertarreservacionActionPerformed(evt);
            }
        });

        btmodificarreservacion.setText("MODIFICAR");
        btmodificarreservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodificarreservacionActionPerformed(evt);
            }
        });

        btsalir.setText("SALIR");
        btsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalirActionPerformed(evt);
            }
        });

        bteliminarreservacion.setText("ELIMINAR");
        bteliminarreservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bteliminarreservacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btinsertarreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmodificarreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btinsertarreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btmodificarreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(bteliminarreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFMenu men = new JFMenu();
        men.setVisible(true);
    }//GEN-LAST:event_btsalirActionPerformed

    private void bteliminarreservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bteliminarreservacionActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Reservacion res = new Reservacion(tfcodigoreservacion.getText(), null, null, null, null, null, null);
        try{
            ObjectSet resul = DB.get(res);

            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :(");
            }
            else
            {
                Doctor edoc = (Doctor)resul.next();
                DB.delete(edoc);
                JOptionPane.showMessageDialog(rootPane, "Datos eliminados exitosamente :(");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se eliminaros exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_bteliminarreservacionActionPerformed

    private void btinsertarreservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinsertarreservacionActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Reservacion res = new Reservacion(tfcodigoreservacion.getText(), tfceduladoctorreservacion.getText(), tfcedulausuarioreservacion.getText(), tfcedularesponsablereservacion.getText(), tfcedulapacientereservacion.getText(), tasintomasreservacion.getText(), jcfechayhorareservacion.getDate());
        try{
            if(Comprobar_Reservacion(DB, tfcodigoreservacion.getText()) == 0){
                DB.store(res);
                DB.commit();
                JOptionPane.showMessageDialog(rootPane, "Datos guardados exitosamente :)");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Estos Datos ya existen :|");
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se guardados exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btinsertarreservacionActionPerformed

    private void btmodificarreservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodificarreservacionActionPerformed
        // TODO add your handling code here:
        ObjectContainer DB = Db4o.openFile("C:\\Users\\MAWIL\\Downloads\\BD Access\\M2C\\clinica2.yap");
        Reservacion res = new Reservacion(tfcodigoreservacion.getText(), null, null, null, null, null, null);
        try{
            ObjectSet resul = DB.get(res);
            if(resul.size() == 0){
                JOptionPane.showMessageDialog(rootPane, "No existen datos :(");
            }
            else
            {
                Reservacion mres = (Reservacion)resul.next();
                mres.setRese_codigo(tfcodigoreservacion.getText());
                mres.setRese_doc_cedula(tfceduladoctorreservacion.getText());
                mres.setRese_res_cedula(tfcedularesponsablereservacion.getText());
                mres.setRese_pac_cedula(tfcedulapacientereservacion.getText());
                mres.setRese_fecha_hora(jcfechayhorareservacion.getDate());
                mres.setRese_sintomas(tasintomasreservacion.getText());
                mres.setRese_usu_cedula(tfcedulausuarioreservacion.getText());
                DB.set(mres);
                JOptionPane.showMessageDialog(rootPane, "Datos actualizados exitosamente :(");
                this.dispose();
                JFMenu men = new JFMenu();
                men.setVisible(true);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Datos no se actualizaron exitosamente :(");
        }finally{
            DB.close();
        }
    }//GEN-LAST:event_btmodificarreservacionActionPerformed

    private void tfcedulausuarioreservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcedulausuarioreservacionFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tfcedulausuarioreservacion.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique la cedula");
        }
    }//GEN-LAST:event_tfcedulausuarioreservacionFocusLost

    private void tfceduladoctorreservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfceduladoctorreservacionFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tfceduladoctorreservacion.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique la cedula");
        }
    }//GEN-LAST:event_tfceduladoctorreservacionFocusLost

    private void tfcedulapacientereservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcedulapacientereservacionFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tfcedulapacientereservacion.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique la cedula");
        }
    }//GEN-LAST:event_tfcedulapacientereservacionFocusLost

    private void tfcedularesponsablereservacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfcedularesponsablereservacionFocusLost
        // TODO add your handling code here:
        if(vali.validaCedulaoTelefono(tfcedularesponsablereservacion.getText()) == false){
            JOptionPane.showMessageDialog(rootPane, "Verifique la cedula");
        }
    }//GEN-LAST:event_tfcedularesponsablereservacionFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bteliminarreservacion;
    private javax.swing.JButton btinsertarreservacion;
    private javax.swing.JButton btmodificarreservacion;
    private javax.swing.JButton btsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.calendar.JDateChooser jcfechayhorareservacion;
    private javax.swing.JTextArea tasintomasreservacion;
    private javax.swing.JTextField tfceduladoctorreservacion;
    private javax.swing.JTextField tfcedulapacientereservacion;
    private javax.swing.JTextField tfcedularesponsablereservacion;
    private javax.swing.JTextField tfcedulausuarioreservacion;
    private javax.swing.JTextField tfcodigoreservacion;
    // End of variables declaration//GEN-END:variables
   
    public static int Comprobar_Reservacion(ObjectContainer base, String rese_codigo){
        Reservacion res = new Reservacion(rese_codigo, null, null, null, null, null, null);
        ObjectSet resul = base.get(res);
        return resul.size();
    } 
}
